# Generated by Django 5.0.3 on 2024-04-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlistapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='qty',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productname',
            new_name='name',
        ),
    ]
