# Generated by Django 5.0.3 on 2024-04-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlistapp', '0002_rename_qty_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.URLField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
