# Generated by Django 5.0.3 on 2024-04-10 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlistapp', '0003_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='Productname',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='Productprice',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='title',
        ),
    ]
